kind: List
apiVersion: v1
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: s2i-dash-base
    labels:
      build: s2i-dash-base
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: s2i-dash-base
    labels:
      build: s2i-dash-base
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
      - type: GitHub
        github:
          secret: "1234567"
    source:
      type: Git
      git:
        uri: https://github.com/vpavlin/dash-openshift.git
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: centos/python-36-centos7:latest
    output:
      to:
        kind: ImageStreamTag
        name: s2i-dash-base:latest
    resources:
      limist:
        memory: 512Mi
